---
apiVersion: v1
kind: Secret
metadata:
  name: dhruv-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZG80bW95dWZzCg==
  CLOUDINARY_KEY: MTMxODU1Mzc3ODY5NDE1Cg==
  CLOUDINARY_SECRET: SnR3TzdrWXNaeXRtckRXX096b2JtTzJJNDRJCg==
  MAPBOX_TOKEN: cGsuZXlKMUlqb2laSE0zTURReUlpd2lZU0k2SW1Oc2RtMTBkV1p6ZFRBMk9Ha3lhM00wYldsdk5XTnJPVzhpZlEuV2pVZE9NYXlfZkNaSHZaM0JaZlI0QQo=
  DB_URL: bW9uZ29kYitzcnY6Ly9kaHJ1djk5OWRkcnI6QUJDREBkaHJ1djEuYWpqbTVteS5tb25nb2RiLm5ldC8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9RGhydXYxCg==
  SECRET: ZGV2b3BzX2JveQo=
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhruv-camp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dhruv-camp
  template:
    metadata:
      labels:
        app: dhruv-camp
    spec:
      containers:
        - name: dhruv-camp-container
          image: dhruv999ddrr/campa:latest
          ports:
            - containerPort: 3000
          env:
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: dhruv-camp-secrets
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_KEY
              valueFrom:
                secretKeyRef:
                  name: dhruv-camp-secrets
                  key: CLOUDINARY_KEY
            - name: CLOUDINARY_SECRET
              valueFrom:
                secretKeyRef:
                  name: dhruv-camp-secrets
                  key: CLOUDINARY_SECRET
            - name: MAPBOX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: dhruv-camp-secrets
                  key: MAPBOX_TOKEN
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: dhruv-camp-secrets
                  key: DB_URL
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: dhruv-camp-secrets
                  key: SECRET
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30   # Adjust the initial delay here
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30   # Adjust the initial delay here

---
apiVersion: v1
kind: Service
metadata:
  name: dhruv-camp-service
spec:
  selector:
    app: dhruv-camp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
